// Precompile ui/*.jsx into ui.bundle.js so the page does not need Babel at
// runtime. Run with `npm run build` after editing anything in ui/.
import { transformAsync } from '@babel/core';
import fs from 'node:fs/promises';
import { createHash } from 'node:crypto';

const FILES = ['ui/kit.jsx', 'ui/panels.jsx', 'ui/app.jsx'];

const parts = [];
for (const file of FILES) {
    const src = await fs.readFile(file, 'utf8');
    const out = await transformAsync(src, {
        filename: file,
        presets: [['@babel/preset-react', { runtime: 'classic' }]],
        comments: false,
        compact: false,
        babelrc: false,
        configFile: false,
    });
    parts.push(`// ── ${file} ──\n${out.code}`);
}

const banner = '// GENERATED by build.mjs from ui/*.jsx — do not edit by hand. Run `npm run build`.\n';
await fs.writeFile('ui.bundle.js', banner + parts.join('\n\n') + '\n');
const size = (await fs.stat('ui.bundle.js')).size;
console.log(`ui.bundle.js written (${(size / 1024).toFixed(1)} KB)`);

// Cache-busting: stamp every local script/stylesheet in index.html with a hash
// of its contents, so returning visitors never get a mix of old and new files.
let html = await fs.readFile('index.html', 'utf8');
const stamped = new Set();
html = await replaceAsync(html, /((?:src|href)=["']|s\.src = ')([\w./-]+\.(?:js|css))\?v=[\w]+/g, async (m, pre, file) => {
    const hash = createHash('sha1').update(await fs.readFile(file)).digest('hex').slice(0, 8);
    stamped.add(file);
    return `${pre}${file}?v=${hash}`;
});
await fs.writeFile('index.html', html);
console.log(`index.html: ${stamped.size} files stamped`);

async function replaceAsync(str, re, fn) {
    const jobs = [];
    str.replace(re, (...a) => { jobs.push(fn(...a)); return ''; });
    const out = await Promise.all(jobs);
    let i = 0;
    return str.replace(re, () => out[i++]);
}
