// Precompile ui/*.jsx into ui.bundle.js so the page does not need Babel at
// runtime. Run with `npm run build` after editing anything in ui/.
import { transformAsync } from '@babel/core';
import fs from 'node:fs/promises';

const FILES = ['ui/kit.jsx', 'ui/panels.jsx', 'ui/app.jsx'];

const parts = [];
for (const file of FILES) {
    const src = await fs.readFile(file, 'utf8');
    const out = await transformAsync(src, {
        filename: file,
        presets: [['@babel/preset-react', { runtime: 'classic' }]],
        comments: false,
        compact: false,
        babelrc: false,
        configFile: false,
    });
    parts.push(`// ── ${file} ──\n${out.code}`);
}

const banner = '// GENERATED by build.mjs from ui/*.jsx — do not edit by hand. Run `npm run build`.\n';
await fs.writeFile('ui.bundle.js', banner + parts.join('\n\n') + '\n');
const size = (await fs.stat('ui.bundle.js')).size;
console.log(`ui.bundle.js written (${(size / 1024).toFixed(1)} KB)`);
